name: "Submit to Chrome/Edge/Firefox Stores"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Read json
        id: read-json
        shell: pwsh
        run: |
          $json = Get-Content ./packages.json | ConvertFrom-Json
          echo "::set-output name=prop::$(echo $json.prop)"
      - run: echo ${{ steps.read-json.outputs.prop}}
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
          run_install: true
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x
          cache: "pnpm"
      - name: Build the extension
        run: pnpm build --zip --target=firefox-mv3
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          artifact: build/firefox-mv3-prod.zip
          verbose: true
