name: "publish-beta"

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: get-version
        shell: pwsh
        run: |
          $json = Get-Content package.json | ConvertFrom-Json
          echo "::set-output name=version::$(echo $json.version)"
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
          run_install: true
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x
          cache: "pnpm"
      - name: Build the extension
        run: pnpm build --zip --target=firefox-mv3
      - name: Rename extension file 
        run: mv build/firefox-mv3-prod.zip build/${{ steps.get-version.outputs.version }}.beta.zip
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          artifact: build/${{ steps.get-version.outputs.version }}.beta.zip
          verbose: true
